name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    name: Build Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-node-${{ matrix.node-version }}
          path: dist/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    name: Test Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  docker:
    needs: build
    runs-on: ubuntu-latest
    name: Docker Build & Push (Node 18 only)
    steps:
      - uses: actions/checkout@v3

      - name: Download dist artifact from Node 18
        uses: actions/download-artifact@v4
        with:
          name: dist-node-18
          path: dist/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-ci-cd-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-ci-cd-app:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.ref_name == 'dev'
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: Show environment variables
        run: |
          echo "Deploying to ${{ github.ref_name }}"
          echo "API_URL=${{ vars.API_URL }}"
          echo "DB_NAME=${{ vars.DB_NAME }}"
